# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
neo_version=21.1.228

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

mod_id = fhcoal
mod_version=1.0.0


quark_version=4.1-480
zeta_version=1.1-40
biolith_version=3.0.10
emi_version=1.1.22+1.21.1

pastel_version=1.1.5.5
databank_version=1.3.1
cloth_config_version=15.0.140
modonomicon_version=1.120.1
curios_version
exclusion_lib_version = 1.1.0

create_version = 6.0.10-280
registrate_version = MC1.21-1.3.0+67
ponder_version = 1.0.82
flywheel_version = 1.0.6

aeronautics_version = 1.2.1
sable_version = 1.2.2
veil_version = 3.6.2

trading_hall_version = 3.0.16

# Still need to add!
farmers_delight_version=1.3.1
